repos:
  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check
        entry: ./gradlew spotlessCheck
        language: system
        types: [java]
        pass_filenames: false
        stages: [commit] # Run on commit

      - id: checkstyle
        name: Checkstyle
        entry: ./gradlew checkstyleMain checkstyleTest
        language: system
        types: [java]
        pass_filenames: false
        stages: [commit] # Run on commit

# To apply formatting automatically on commit, uncomment this hook
# and comment out the spotless-check hook above.
# -   id: spotless-apply
#     name: Spotless Apply
#     entry: ./gradlew spotlessApply
#     language: system
#     types: [java]
#     pass_filenames: false
#     stages: [commit]
