repos:
  - repo: local
    hooks:
      - id: spotless-apply
        name: Spotless Apply
        entry: ./gradlew spotlessApply
        language: system
        types: [java]
        pass_filenames: false
        stages: [commit]

      - id: spotless-check
        name: Spotless Check
        entry: ./gradlew spotlessCheck
        language: system
        types: [java]
        pass_filenames: false
        stages: [commit]

      - id: checkstyle
        name: Checkstyle
        entry: ./gradlew checkstyleMain checkstyleTest
        language: system
        types: [java]
        pass_filenames: false
        stages: [commit]
