rootProject.name = "java-cookbook"

// Recipe modules will be included here as they are added, e.g.:
include("strategy-pattern")
include("factory-pattern")
include("builder-pattern")
include("observable-pattern")
include("singleton-pattern")
include("generics")
include("json-handling")
include("yaml-handling")
include("http-requests")
include("records")
include("error-logging")
include("try-with-resources")
include("annotations")
include("jdbc-postgres")
include("mongodb-driver")
include("redis-clients")
include("generics-deep-dive")
include("functional-programming")
include("packaging-distribution")
include("api-development")
include("concurrent-processing")
include("property-based-testing")
include("event-driven-programming")
include("async-programming")
include("metaprogramming")
include("performance-optimization")
include("memory-management")
include("jni-jna") 